on: [push]

jobs:
  whylogs_constraints_job:
    runs-on: ubuntu-latest
    name: validates data against whylogs constraints
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: whylogs constraint validation step
        uses: ./ # Uses an action in the root directory
        id: whylogs
        with:
          constraintsfile: 'constraints.json'
          datafile: 'lending_club_1000.csv'
